# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


use_frameworks!

target 'Fireless' do
pod 'Firebase'
pod 'Firebase/Database'
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Core'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

end

